version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Test
          command: bundle exec rake test

workflows:
  build_and_test:
    jobs:
      - test
